version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/test_db
      - STORE_DATA_CSV=/data/store-status.csv
      - BUSINESS_HOURS_CSV=/data/menu-hours.csv
      - TIMEZONES_CSV=/data/timezones.csv
    volumes:
      - ./app:/app
      - ./data:/app/data  # Add this line to mount the data directory
    working_dir: /app

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
